config/routes.rb
Rails.application.routes.draw do
  resources :weathers

end

app/models/weather.rb
class Weather < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    byebug
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render :show, status: :created, location: @weather }
      else
        format.html { render :new }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url, notice: 'Weather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_params
      params.require(:weather).permit(:temprature, :humidity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeController</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weathers/_form.html.erb
<%= form_for(@weather) do |f| %>
  <% if @weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% @weather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temprature %><br>
    <%= f.text_field :temprature %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br>
    <%= f.text_field :humidity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weathers/edit.html.erb
<h1>Editing Weather</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

app/views/weathers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weathers</h1>

<table>
  <thead>
    <tr>
      <th>Temprature</th>
      <th>Humidity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.temprature %></td>
        <td><%= weather.humidity %></td>
        <td><%= link_to 'Show', weather %></td>
        <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
        <td><%= link_to 'Destroy', weather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather', new_weather_path %>

app/views/weathers/new.html.erb
<h1>New Weather</h1>

<%= render 'form' %>

<%= link_to 'Back', weathers_path %>

app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temprature:</strong>
  <%= @weather.temprature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @weather.humidity %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>